import {useState} from "react";
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {PassportVerifier} from "@gitcoinco/passport-sdk-verifier";

export default function Home() {
  const [addressInput, setAddressInput] = useState("");
  const [passport, setPassport] = useState({});

  // override default ceramic node url. Default is the passport-iam prod ceramic node.
  const verifier = new PassportVerifier(
    "https://ceramic.staging.dpopp.gitcoin.co"
  );

  const handleSubmit = (event) => {
    event.preventDefault();
    verifier.verifyPassport(addressInput).then((result) => {
      setPassport(result);
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <img src="GitcoinLogo.svg" alt="logo"/>
        <h1>Passport Verifier SDK</h1>
        <p>Enter Wallet Address to verify passport</p>
        <form>
          <input
            type="text"
            name="inputAddress"
            style={{padding: 12}}
            // @ts-ignore
            onChange={(e) => setAddressInput(e.target.value)}
            value={addressInput}
          />
          <button style={{padding: 12}} onClick={handleSubmit}>
            Enter
          </button>
        </form>
        {passport && (
          <div
            style={{
              padding: 10,
              marginTop: 10,
              fontSize: 14,
              textAlign: "left",
            }}
          >
            <h1 style={{textAlign: "center"}}>Passport Stamps</h1>
            {
              // @ts-ignore
              passport?.stamps?.length > 0 && (
                <div>
                  Stamps:{" "}
                  <ul>
                    {
                      // @ts-ignore
                      passport?.stamps?.map((item, index) => {
                        return (
                          <li key={index}>
                            {item.provider}: {item.verified ? "✅" : "❌"}
                          </li>
                        );
                      })
                    }
                  </ul>
                </div>
              )
            }
          </div>
        )}
      </main>
    </div>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //
    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>
    //
    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.js</code>
    //     </p>
    //
    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>
    //
    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>
    //
    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>
    //
    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>
    //
    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  )
}
